// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupRolloutPrefs.network.http.http3.enable_0rtt", false);
user_pref("app.normandy.startupRolloutPrefs.network.http.http3.enabled", true);
user_pref("app.normandy.user_id", "f12487f8-3d58-4a67-b771-3cc20a8d5ddc");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1623243676);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1623243002);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1623252383);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1623243706);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1623242992);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 109);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e87c3d02-5e49-4b57-882c-720518035145}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1623242997);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1623251794253");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1623253573253");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1623243001913");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1623264601913");
user_pref("browser.search.region", "BR");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210527174632");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1623252383");
user_pref("browser.startup.homepage_override.buildID", "20210527174632");
user_pref("browser.startup.homepage_override.mstone", "89.0");
user_pref("browser.startup.lastColdStartupCheck", 1623252383);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1623242998789");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "89.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "f2404f8c5d8946e3b11de3848335ea2c");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210527174632");
user_pref("extensions.lastAppVersion", "89.0");
user_pref("extensions.lastPlatformVersion", "89.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"81ec2eef-e506-48f9-8db7-a5a03f7663dc\",\"formautofill@mozilla.org\":\"e4051275-d2dd-4977-a2a2-0ab834ea7faa\",\"pictureinpicture@mozilla.org\":\"1ffb5360-3613-4025-a055-9415b8669563\",\"screenshots@mozilla.org\":\"f3d62888-887b-4fa0-b9e2-3069f744dd8a\",\"webcompat-reporter@mozilla.org\":\"e2c117e5-85b2-490d-a1ee-aea9a8261efc\",\"webcompat@mozilla.org\":\"c493a8cb-b00d-48a1-8742-1236661868d5\",\"default-theme@mozilla.org\":\"0870c2db-f0fc-4b1e-8128-9c51616cdfa0\",\"google@search.mozilla.org\":\"7676ab20-4ff8-4a70-a540-971617885feb\",\"wikipedia@search.mozilla.org\":\"31188ab0-1819-4d3a-88a4-dc388f60edbe\",\"mercadolivre@search.mozilla.org\":\"50ae5642-7688-4361-9953-6fa67cf6e287\",\"bing@search.mozilla.org\":\"1013d798-5553-414d-8e9b-4a653b891ee5\",\"ddg@search.mozilla.org\":\"7004a4d4-20c3-4479-9d19-342075d6a7e8\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1623242998);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgradeDialog-defaultEnabled\",\"enabled\":true,\"targeting\":\"true\",\"variables\":{},\"description\":\"Turn on upgradeDialog by default for all users\"}");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "aac90727-4a05-4644-b491-2067ce01a1a2");
user_pref("toolkit.startup.last_success", 1623252381);
user_pref("toolkit.telemetry.cachedClientID", "48b737f8-9e73-4d51-8bf5-8f3bf5f4e52e");
user_pref("toolkit.telemetry.previousBuildID", "20210527174632");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
